# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQgI81d2NmP7mhvdKY5i4n2xS1eskqA4
"""



"""2nd

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("gender_submission.csv")
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()

sns.countplot(x='Survived', data=df)
plt.title("Survival Distribution in Gender Submission Dataset")
plt.show()

df['Survived'].value_counts(normalize=True) * 100
plt.figure(figsize=(8,4))
plt.plot(df['PassengerId'], df['Survived'], '.')
plt.title("PassengerId vs Survival")
plt.xlabel("PassengerId")
plt.ylabel("Survived")
plt.show()

df.groupby('Survived').count()

print("""
Key Findings:
1. Dataset contains only PassengerId and Survived.
2. No missing or duplicate values found.
3. Survival distribution is imbalanced.
4. PassengerId has no analytical significance.
5. Dataset is meant for submission, not deep EDA.
""")
